export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST"
export const FETCH_PRODUCTS_SUCSESS = "FETCH_PRODUCTS_SUCSESS"
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE"
export const FETCH_PRODUCTS_UPDATE = "FETCH_PRODUCTS_UPDATE"

export const FETCH_TOPSALES_REQUEST = "FETCH_TOPSALES_REQUEST"
export const FETCH_TOPSALES_SUCSESS = "FETCH_TOPSALES_SUCSESS"
export const FETCH_TOPSALES_FAILURE = "FETCH_TOPSALES_FAILURE"

export const CHECK_CATEGORY = "CHECK_CATEGORY"

export const ADD_CART = "ADD_CART"
export const DELETE_CART = "DELETE_CART"

export const SEARCH_PRODUCTS_REQUEST = "SEARCH_PRODUCTS_REQUEST"
export const SEARCH_PRODUCTS_FAILURE = "SEARCH_PRODUCTS_FAILURE"
export const SEARCH_PRODUCTS_SUCCESS = "SEARCH_PRODUCTS_SUCCESS"
export const CHANGE_PRODUCTS_FIELD = "CHANGE_PRODUCTS_FIELD"